# backend/Dockerfile

FROM python:3.11-slim

WORKDIR /app

# Копируем зависимости
COPY backend/requirements.txt .

# Ставим зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код приложения
COPY backend/ .

# Открываем порт
EXPOSE 8000

# Запускаем Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
